name: Build ProGrammar
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and upload ProGrammar
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    runs-on: "macos-14"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: "15.4.0"

      - name: Setup build environment
        run: make setup

      - name: Build ProGrammar
        run: make build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Convert to IPA
        run: make ipa

      - name: Upload ProGrammar.ipa Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProGrammar.ipa
          path: ProGrammar.ipa
