name: Build Prolingo
on:
  #  Workflow dispatch
  workflow_dispatch:

jobs:
  build:
    name: Build and upload Prolingo
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "macos-12"
            version: "14.2"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Setup build environment
        run: make setup

      - name: Build Prolingo
        run: make build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Convert to IPA
        run: make ipa

      - name: Upload Prolingo.ipa Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Prolingo.ipa
          path: Prolingo.ipa
